// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4_0iYDWdZKs6l3nA6NqigjZad4c6-5Bw',
    appId: '1:40033899232:web:5f34590614cdb8b545b685',
    messagingSenderId: '40033899232',
    projectId: 'flash-chat-27d81',
    authDomain: 'flash-chat-27d81.firebaseapp.com',
    storageBucket: 'flash-chat-27d81.appspot.com',
    measurementId: 'G-XPEDC35E32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGdEzmYs8-6Lj7y335g_FKEQhCgaHoudU',
    appId: '1:40033899232:android:1a6c68c7d62d868a45b685',
    messagingSenderId: '40033899232',
    projectId: 'flash-chat-27d81',
    storageBucket: 'flash-chat-27d81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5uhXDepAVYjRW0jKI2LVSyDg0sXSvhuc',
    appId: '1:40033899232:ios:646e3d010082620545b685',
    messagingSenderId: '40033899232',
    projectId: 'flash-chat-27d81',
    storageBucket: 'flash-chat-27d81.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5uhXDepAVYjRW0jKI2LVSyDg0sXSvhuc',
    appId: '1:40033899232:ios:646e3d010082620545b685',
    messagingSenderId: '40033899232',
    projectId: 'flash-chat-27d81',
    storageBucket: 'flash-chat-27d81.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4_0iYDWdZKs6l3nA6NqigjZad4c6-5Bw',
    appId: '1:40033899232:web:c0d493714b46265245b685',
    messagingSenderId: '40033899232',
    projectId: 'flash-chat-27d81',
    authDomain: 'flash-chat-27d81.firebaseapp.com',
    storageBucket: 'flash-chat-27d81.appspot.com',
    measurementId: 'G-2V0Y7KVR9D',
  );
}
